---
title: "Descriptive_epi4"
author: "AKW"
date: "2025-04-02"
output: html_document
---

```{r}
# import the linelist
library(readxl)
linelist_cleaned <- read_excel("~/repository/data/linelist_cleaned.xlsx")
View(linelist_cleaned)

```



```{r}
library(skimr)
skim(linelist_cleaned)


```
```{r}
library(janitor)
linelist_cleaned %>% tabyl(age_cat)

linelist_cleaned %>% tabyl(age_cat, gender)

linelist_cleaned %>%               # case linelist
  tabyl(age_cat) %>%       # tabulate counts and proportions by age category
  adorn_pct_formatting()   # convert proportions to percents

#more descriptive
linelist_cleaned %>%                                  
  tabyl(age_cat, gender) %>%                  # counts by age and gender
  adorn_totals(where = "both") %>%             # add total row
  adorn_percentages(denominator = "row") %>%  # convert counts to proportions
  adorn_pct_formatting(digits = 1)            # convert proportions to percents

linelist_cleaned %>%                                  # case linelist
  tabyl(age_cat, gender) %>%                  # cross-tabulate counts
  adorn_totals(where = "row") %>%             # add a total row
  adorn_percentages(denominator = "col") %>%  # convert to proportions
  adorn_pct_formatting() %>%                  # convert to percents
  adorn_ns(position = "front") %>%            # display as: "count (percent)"
  adorn_title(                                # adjust titles
    row_name = "Age Category",
    col_name = "Gender")

linelist_cleaned%>%
  tabyl(age_cat5)%>%
  adorn_totals(where = "row")%>%
  adorn_pct_formatting()

```
```{r}
linelist_cleaned %>%
  tabyl(age_cat, gender) %>% 
  adorn_totals(where = "both") %>% 
  adorn_percentages(denominator = "col") %>% 
  adorn_pct_formatting() %>% 
  adorn_ns(position = "front") %>% 
  adorn_title(
    row_name = "Age Category",
    col_name = "Gender",
    placement = "combined") %>% # this is necessary to print as image
  flextable::flextable() %>%    # convert to pretty image
  flextable::autofit()          # format to one line per row 

```

# adorn on other tables
```{r}
library(dplyr)
linelist_cleaned %>% 
  count(hospital) %>%   # dplyr function
  adorn_totals()        # janitor function

```
# table presentation
```{r}
linelist_cleaned %>%
  tabyl(age_cat, gender) %>% 
  adorn_totals(where = "both") %>% 
  adorn_percentages(denominator = "col") %>% 
  adorn_pct_formatting() %>% 
  adorn_ns(position = "front") %>% 
  adorn_title(
    row_name = "Age Category",
    col_name = "Gender",
    placement = "combined") %>% 
  flextable::flextable() %>%                    
  flextable::autofit() %>%                     
  flextable::save_as_docx(path = "tabyl.docx")   # save as Word document to filepath

```


# crosstabs
```{r}
library(stats)
age_by_outcome <- linelist_cleaned %>% 
  tabyl(age_cat, outcome, show_na = FALSE) 

chisq.test(age_by_outcome)

```
```{r}
by_hospital <- linelist_cleaned %>% 
  filter(!is.na(outcome) & hospital != "Missing") %>%  # Remove cases with missing outcome or hospital
  group_by(hospital, outcome) %>%                      # Group data
  summarise(                                           # Create new summary columns of indicators of interest
    N = n(),                                            # Number of rows per hospital-outcome group     
    ct_value = median(ct_blood, na.rm=T))               # median CT value per group
  
by_hospital # print table
totals <- linelist_cleaned %>% 
      filter(!is.na(outcome) & hospital != "Missing") %>%
      group_by(outcome) %>%                            # Grouped only by outcome, not by hospital    
      summarise(
        N = n(),                                       # These statistics are now by outcome only     
        ct_value = median(ct_blood, na.rm=T))

totals # print table

table_long <- bind_rows(by_hospital, totals) 

table_long %>% 
  pivot_wider(                                         # Pivot from long to wide
    values_from = c(ct_value, N),                       # new values are from ct and count columns
    names_from = outcome) %>%                           # new column names are from outcomes
  mutate(                                              # Add new columns
    N_Known = N_Death + N_Recover,                               # number with known outcome
    Pct_Death = scales::percent(N_Death / N_Known, 0.1),         # percent cases who died (to 1 decimal)
    Pct_Recover = scales::percent(N_Recover / N_Known, 0.1)) %>% # percent who recovered (to 1 decimal)
  select(                                              # Re-order columns
    hospital, N_Known,                                   # Intro columns
    N_Recover, Pct_Recover, ct_value_Recover,            # Recovered columns
    N_Death, Pct_Death, ct_value_Death)  %>%             # Death columns
  arrange(N_Known)%>%                                  # Arrange rows from lowest to highest (Total row at bottom)
flextable::flextable() %>%                    
  flextable::autofit()

```
# tests
```{r}
library(gtsummary)
linelist_cleaned %>% 
  select(age_years, outcome) %>%             # keep variables of interest
  tbl_summary(                               # produce summary table
    statistic = age_years ~ "{mean} ({sd})", # specify what statistics to show
    by = outcome) %>%                        # specify the grouping variable
  add_p(age_years ~ "t.test")                # specify what tests to perform

linelist_cleaned %>% 
  select(gender, outcome) %>%    # keep variables of interest
  tbl_summary(by = outcome) %>%  # produce summary table and specify grouping variable
  add_p()                        # specify what test to perform

```

```{r}
library(corrr)
correlation_tab <- linelist_cleaned %>% 
  select(generation, age, ct_blood, days_onset_hosp, wt_kg, ht_cm) %>%   # keep numeric variables of interest
  correlate()      # create correlation table (using default pearson)

correlation_tab
rplot(correlation_tab)

```





